[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
"clap" = { version = "4.5.23", features = ["derive"] }
"phf" = { version = "0.11.2", features = ["macros"] }
"simple-error" = "0.3.1"
"regex" = "1.11.1"
lazy_static = "1.5.0"
itertools = "0.13.0"
num-traits = "0.2.19"
